version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Lambdadeploysma"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hy8fer1yp1mt"
s3_prefix = "Lambdadeploysma"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
